name: CI Ubuntu
on: [push, pull_request]
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
        - '5.30'
    container:
      image: perl:${{matrix.perl-version}}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: perl -V
      run: perl -V
    - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
      run: cpanm -n App::cpanminus ExtUtils::MakeMaker
    - name: Install dependencies
      run: |
        cpanm -n --installdeps .
        cpanm -n Test::Pod Test::Pod::Coverage
    - name: Run tests
      run: prove -vl t/*.t
      env:
        TEST_CSS: 1
        TEST_JS: 1
        TEST_NPM: 1
        TEST_POD: 1
        TEST_ROLLUP: 1
        TEST_WEBPACK: 1
